# Generated by Django 3.2.2 on 2021-10-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Villians',
            new_name='Villain',
        ),
    ]
